import { PersonaThemeDefinition } from "../theme-engine";
import { PERSONA_SYSTEM_PROMPTS } from "../persona-prompts";
import { narutoTheme } from "./naruto";

export const allThemes: PersonaThemeDefinition[] = [
  narutoTheme,
  {
    id: "sasuke",
    name: "Саске (Sharingan / Rinnegan)",
    primaryColor: "#8A2BE2",
    backgroundColor: "#08060C",
    accentColor: "#DC143C",
    systemPrompt: PERSONA_SYSTEM_PROMPTS.sasuke,
    sfxSend: "assets/sasuke/sfx_katana.wav",
    sfxSuccess: "assets/sasuke/sfx_chidori_success.mp3",
    sfxError: "assets/sasuke/sfx_usuratonkachi_error.mp3",
    videoOverlay: "assets/sasuke/video_rinnegan_distortion.webm",
    cssClass: "theme-sasuke",
  },
  {
    id: "geralt",
    name: "Геральт (The Witcher)",
    primaryColor: "#C0C0C0",
    backgroundColor: "#1E222A",
    accentColor: "#FFBF00",
    systemPrompt: PERSONA_SYSTEM_PROMPTS.geralt,
    sfxSend: "assets/geralt/sfx_draw_sword.wav",
    sfxSuccess: "assets/geralt/sfx_coin_toss.mp3",
    sfxError: "assets/geralt/sfx_zaraza.mp3",
    videoOverlay: "assets/geralt/video_medallion_aura.webm",
    cssClass: "theme-geralt",
  },
  {
    id: "assassins",
    name: "Ассасины (Ezio / Altaïr)",
    primaryColor: "#E63946",
    backgroundColor: "#F5F5F7",
    accentColor: "#1A1A1D",
    systemPrompt: PERSONA_SYSTEM_PROMPTS.assassins,
    sfxSend: "assets/assassins/sfx_hidden_blade.wav",
    sfxSuccess: "assets/assassins/sfx_sync_success.mp3",
    sfxError: "assets/assassins/sfx_desync.wav",
    videoOverlay: "assets/assassins/video_animus_grid.webm",
    cssClass: "theme-assassins",
  },
  {
    id: "musk",
    name: "Илон Маск (SpaceX / Cybertruck)",
    primaryColor: "#FF4500",
    backgroundColor: "#0B0F19",
    accentColor: "#D1D5DB",
    systemPrompt: PERSONA_SYSTEM_PROMPTS.musk,
    sfxSend: "assets/musk/sfx_raptor_ignition.wav",
    sfxSuccess: "assets/musk/sfx_landing_cheers.mp3",
    sfxError: "assets/musk/sfx_rud_explosion.mp3",
    videoOverlay: "assets/musk/video_telemetry.webm",
    cssClass: "theme-musk",
  },
  {
    id: "durov",
    name: "Павел Дуров (TON / Privacy)",
    primaryColor: "#0088CC",
    backgroundColor: "#000000",
    accentColor: "#FFFFFF",
    systemPrompt: PERSONA_SYSTEM_PROMPTS.durov,
    sfxSend: "assets/durov/sfx_plane_swish.wav",
    sfxSuccess: "assets/durov/sfx_ton_success.mp3",
    sfxError: "assets/durov/sfx_privacy_block.wav",
    videoOverlay: "assets/durov/video_ton_stream.webm",
    cssClass: "theme-durov",
  },
  {
    id: "spidey",
    name: "Человек-Паук (Peter Parker)",
    primaryColor: "#E50914",
    backgroundColor: "#0A0E17",
    accentColor: "#0066FF",
    systemPrompt: PERSONA_SYSTEM_PROMPTS.spidey,
    sfxSend: "assets/spidey/sfx_thwip.wav",
    sfxSuccess: "assets/spidey/sfx_yahoo.mp3",
    sfxError: "assets/spidey/sfx_spider_alarm.wav",
    videoOverlay: "assets/spidey/video_web_hud.webm",
    cssClass: "theme-spidey",
  },
  {
    id: "wot",
    name: "Командир Танков (WoT / Lesta)",
    primaryColor: "#FFCC00",
    backgroundColor: "#1B1E16",
    accentColor: "#4B5320",
    systemPrompt: PERSONA_SYSTEM_PROMPTS.wot,
    sfxSend: "assets/wot/sfx_cannon_shot.wav",
    sfxSuccess: "assets/wot/sfx_probitie.mp3",
    sfxError: "assets/wot/sfx_ricochet.mp3",
    videoOverlay: "assets/wot/video_reticle.webm",
    cssClass: "theme-wot",
  },
  {
    id: "valera",
    name: "Валера (Цифровой Сантехник)",
    primaryColor: "#1D4ED8",
    backgroundColor: "#111827",
    accentColor: "#C2410C",
    systemPrompt: PERSONA_SYSTEM_PROMPTS.valera,
    sfxSend: "assets/valera/sfx_wrench_hit.wav",
    sfxSuccess: "assets/valera/sfx_water_flow.mp3",
    sfxError: "assets/valera/sfx_pipe_burst.mp3",
    videoOverlay: "assets/valera/video_pipes_overlay.webm",
    cssClass: "theme-valera",
  },
];
